name: Patch and Build

on:
  push:
    branches: [ "1.21" ]
  workflow_dispatch:
  #workflow_run:
    #workflows: ["Automatically update Folia commit"]
   # types:
     # - completed

jobs:
  compile_1_21_core_jar:
    runs-on: windows-latest
    
    permissions:
       contents: write
       actions: write
       
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
        
      - name: Configure Git User Details
        run: |
          git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"

      - name: Apply Patches
        run: ./gradlew applyPatches
   
      - name: Build
        run: ./gradlew createReobfPaperclipJar createMojmapPaperclipJar
           
      - name: Make release
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "Foldenor 1.21 release"
          body: |
            Foldenor build
            Version: 1.21
          tag_name: "1.21"
          files: build/libs/*
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
